version: "3"
services:
  neuralcomposer:
    container_name: neuralcomposer
    image: "node:10-buster-slim"
    user: "node"
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node
    restart: unless-stopped
    ports:
      - "86:5000/tcp"
    command: "node src/server/index.js"
